[build]
  base    = "client"         # build inside the client folder
  command = "npm run build"
  publish = "client/dist"    # Vite’s default output inside client/

# SPA rewrite so /dashboard etc. don’t 404
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Proxy API to your backend host (replace the URL)
[[redirects]]
  from = "/api/*"
  to   = "https://YOUR-BACKEND-HOST/:splat"
  status = 200
  force  = true
